# Docker Compose Spec Version
version: '3.9'

services:

  carma-config:
    image: quitter.tech/carma-config:c1tenth-develop
    command: sh
    stdin_open: true
    tty: true

  platform_ros1:
    image: quitter.tech/carma-platform:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from: 
      - carma-config
    volumes:
      - /home/c1t-graytruck/carma-platform/carma/launch:/opt/carma/launch/minimal      
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    command: bash -c 'wait-for-it.sh localhost:11311 && source /opt/carma/install/setup.bash && roslaunch /opt/carma/launch/minimal/carma_docker.launch'

  platform_ros2:
    image: quitter.tech/carma-platform:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from:
      - carma-config
    volumes:
      - /home/c1t-graytruck/carma-platform/carma/launch:/opt/carma/launch/minimal
      - /home/c1t-graytruck/carma-platform/system_controller/config:/opt/carma/install_ros2/system_controller/share/system_controller/config  
      - /home/c1t-graytruck/carma-platform/subsystem_controllers/config:/opt/carma/install_ros2/subsystem_controllers/share/system_controller/config     
    command: bash -c 'wait-for-it.sh localhost:11311 && source /opt/carma/install_ros2/setup.bash && ros2 launch /opt/carma/launch/minimal/carma_docker.launch.py'
   
  mock-drivers:
    image: quitter.tech/carma-platform:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from:
      - carma-config
    entrypoint: ""
    command: bash -c 'export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 && source /opt/carma/install/setup.bash && roslaunch carma mock_drivers.launch'