# Docker Compose Spec Version
version: '3.9'

services:

  carma-config:
    image: quitter.tech/carma-config:c1tenth-develop
    command: sh
    stdin_open: true
    tty: true

  carma-web-ui:
    container_name: carma-web-ui    
    image: quitter.tech/carma-web-ui:c1tenth-develop
    depends_on:
      - carma-config
    ipc: host
    network_mode: host
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    volumes_from:
      - carma-config
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: always

  roscore:
    image: quitter.tech/carma-base:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from: 
      - carma-config
    restart: always
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    command: roscore

  platform_ros1:
    image: quitter.tech/carma-platform:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from: 
      - carma-config
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    command: bash -c 'wait-for-it.sh localhost:11311 && source /opt/carma/install/setup.bash && roslaunch /opt/carma/vehicle/config/carma_docker.launch'

  platform_ros2:
    image: quitter.tech/carma-platform:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from:
      - carma-config
    command: bash -c 'wait-for-it.sh localhost:11311 && source /opt/carma/install_ros2/setup.bash && ros2 launch /opt/carma/vehicle/config/carma_docker.launch.py'

  ros1_bridge:
    image: quitter.tech/carma-msgs:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from:
      - carma-config
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    command: bash -c 'wait-for-it.sh localhost:11311 -- rosparam load /opt/carma/vehicle/config/bridge.yml && source ~/.base-image/workspace/install/setup.bash && ros2 run ros1_bridge dynamic_bridge --multi-threads'

  drivers:
    image: quitter.tech/c1tenth-driver-wrappers:c1tenth-develop
    ipc: host
    network_mode: host
    devices:
      - /dev/sensors/imu
      - /dev/sensors/rplidar
      - /dev/sensors/vesc
      - /dev/input/js0
    volumes_from:
      - carma-config
    command: bash -c 'source /home/carma/install/setup.bash && ros2 launch c1tenth_drivers c1tenth_drivers.launch.py'
  
  v2x:
    image: quitter.tech/carma-cohda-dsrc-driver:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from:
      - carma-config
    command: bash -c 'source /opt/carma/install/setup.bash && ros2 launch /opt/carma/vehicle/config/drivers.launch.py drivers:=dsrc_driver'
