# Docker Compose Spec Version
version: '3.9'

services:

  carma-config:
    image: quitter.tech/carma-config:c1tenth-develop
    command: sh
    stdin_open: true
    tty: true

  # carma-web-ui:
  #   image: quitter.tech/carma-web-ui:c1tenth-develop
  #   depends_on:
  #     - carma-config
  #   ipc: host
  #   network_mode: host
  #   environment:
  #     - ROS_IP=127.0.0.1
  #     - ROS_MASTER_URI=http://127.0.0.1:11311
  #   volumes_from:
  #     - carma-config
  #   volumes: 
  #     - /var/run/docker.sock:/var/run/docker.sock 
  #   restart: always

  roscore:
    image: quitter.tech/carma-base:c1tenth-develop
    ipc: host
    network_mode: host
    container_name: roscore    
    volumes_from: 
      - carma-config
    restart: always
    environment:
      - ROS_IP=127.0.0.1
    command: roscore

  platform:
    image: quitter.tech/carma-platform:c1tenth-develop
    container_name: platform
    network_mode: host
    volumes_from: 
      - carma-config
    # volumes:
    #   - /opt/carma/logs:/opt/carma/logs
    #   - /opt/carma/.ros:/home/carma/.ros
    #   - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
    #   - /opt/carma/yolo:/opt/carma/yolo
    #   - /opt/carma/maps:/opt/carma/maps
    #   - /opt/carma/routes:/opt/carma/routes
    #   - /opt/carma/data:/opt/carma/data
    #   - ~/carma_ws/src/carma-platform/carma/launch:/opt/carma/install/carma/share/carma/launch
    environment:
      - ROS_IP=127.0.0.1
    command: bash -c 'wait-for-it.sh localhost:11311 -- roslaunch /opt/carma/vehicle/config/carma_docker.launch'

  platform_ros2:
    image: quitter.tech/carma-platform:c1tenth-develop
    network_mode: host
    container_name: platform_ros2
    volumes_from:
      - carma-config
    # volumes:
      # - /opt/carma/logs:/opt/carma/logs
      # - /opt/carma/.ros:/home/carma/.ros
      # - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
      # - /opt/carma/maps:/opt/carma/maps
      # - /opt/carma/routes:/opt/carma/routes
      # - /opt/carma/yolo:/opt/carma/yolo
      # - ~/carma_ws/src/carma-platform/carma/launch:/opt/carma/install_ros2/carma/share/carma/launch
      # - ~/carma_ws/src/carma-platform/system_controller/config:/opt/carma/install_ros2/system_controller/share/system_controller/config
#      - ~/carma_ws/src/carma-platform/subsystem_controllers/config:/opt/carma/install_ros2/subsystem_controllers/share/subsystem_controllers/config
    command: bash -c 'source /opt/carma/install_ros2/setup.bash && ros2 launch /opt/carma/vehicle/config/carma_docker.launch.py'

  ros1_bridge:
    image: quitter.tech/carma-msgs:c1tenth-develop
    network_mode: host
    volumes_from:
      - carma-config
    environment:
      - ROS_IP=127.0.0.1
    # volumes:
    #   - /opt/carma/logs:/opt/carma/logs
    #   - /opt/carma/.ros:/home/carma/.ros
    #   - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
    #   - /opt/carma/maps:/opt/carma/maps
    #   - /opt/carma/routes:/opt/carma/routes
    #   - /opt/carma/yolo:/opt/carma/yolo      
    command: bash -c 'wait-for-it.sh localhost:11311 && rosparam load /opt/carma/vehicle/config/bridge.yml && source ~/.base-image/workspace/install/setup.bash && ros2 run ros1_bridge dynamic_bridge --multi-threads'

  mock-lightbar-driver:
    image: quitter.tech/carma-platform:c1tenth-develop
    network_mode: host
    container_name: carma-mock-lightbar-driver
    volumes_from: 
      - carma-config
    # volumes:
    #   - /opt/carma/logs:/opt/carma/logs
    #   - /opt/carma/.ros:/home/carma/.ros
    #   - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
    #   - /opt/carma/data:/opt/carma/data
    environment:
      - ROS_IP=127.0.0.1
    command: bash -c 'export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 -- roslaunch carma mock_drivers.launch mock_drivers:="lightbar bag_parser"'

  mock-can-driver:
    image: quitter.tech/carma-platform:c1tenth-develop
    network_mode: host
    container_name: carma-mock-can-driver
    volumes_from: 
      - carma-config
    # volumes:
    #   - /opt/carma/logs:/opt/carma/logs
    #   - /opt/carma/.ros:/home/carma/.ros
    #   - /opt/carma/data:/opt/carma/data
    environment:
      - ROS_IP=127.0.0.1
    command: bash -c 'export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 -- roslaunch carma mock_drivers.launch mock_drivers:=can'

  mock-comms-driver:
    image: quitter.tech/carma-platform:c1tenth-develop
    network_mode: host
    container_name: carma-mock-comms-driver
    volumes_from: 
      - carma-config
    # volumes:
    #   - /opt/carma/logs:/opt/carma/logs
    #   - /opt/carma/.ros:/home/carma/.ros
    #   - /opt/carma/data:/opt/carma/data
    environment:
      - ROS_IP=127.0.0.1
    command: bash -c 'export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 -- roslaunch carma mock_drivers.launch mock_drivers:=comms'

  mock-controller-driver:
    image: quitter.tech/carma-platform:c1tenth-develop
    network_mode: host
    container_name: carma-srx-controller-driver
    volumes_from: 
      - carma-config
    # volumes:
    #   - /opt/carma/logs:/opt/carma/logs
    #   - /opt/carma/.ros:/home/carma/.ros
    #   - /opt/carma/data:/opt/carma/data
    environment:
      - ROS_IP=127.0.0.1
    command: bash -c 'export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 -- roslaunch carma mock_drivers.launch mock_drivers:=controller'

  mock-radar-driver:
    image: quitter.tech/carma-platform:c1tenth-develop
    network_mode: host
    container_name: carma-mock-radar-driver
    volumes_from: 
      - carma-config
    # volumes:
    #   - /opt/carma/logs:/opt/carma/logs
    #   - /opt/carma/.ros:/home/carma/.ros
    #   - /opt/carma/data:/opt/carma/data
    environment:
      - ROS_IP=127.0.0.1
    command: bash -c 'export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 -- roslaunch carma mock_drivers.launch mock_drivers:=radar'

  mock-gnss-driver:
    image: quitter.tech/carma-platform:c1tenth-develop
    network_mode: host
    container_name: carma-mock-gnss-driver
    volumes_from: 
      - carma-config
    # volumes:
    #   - /opt/carma/logs:/opt/carma/logs
    #   - /opt/carma/.ros:/home/carma/.ros
    #   - /opt/carma/data:/opt/carma/data
    environment:
      - ROS_IP=127.0.0.1
    command: bash -c 'export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 -- roslaunch carma mock_drivers.launch mock_drivers:=gnss'

  mock-imu-driver:
    image: quitter.tech/carma-platform:c1tenth-develop
    network_mode: host
    container_name: carma-mock-imu-driver
    volumes_from: 
      - carma-config
    # volumes:
    #   - /opt/carma/logs:/opt/carma/logs
    #   - /opt/carma/.ros:/home/carma/.ros
    #   - /opt/carma/data:/opt/carma/data
    environment:
      - ROS_IP=127.0.0.1
    command: bash -c 'export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 -- roslaunch carma mock_drivers.launch mock_drivers:=imu'

  mock-lidar-driver:
    image: quitter.tech/carma-platform:c1tenth-develop
    network_mode: host
    container_name: carma-mock-lidar-driver
    volumes_from: 
      - carma-config
    # volumes:
    #   - /opt/carma/logs:/opt/carma/logs
    #   - /opt/carma/.ros:/home/carma/.ros
    #   - /opt/carma/data:/opt/carma/data
    environment:
      - ROS_IP=127.0.0.1
    command: bash -c 'export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 -- roslaunch carma mock_drivers.launch mock_drivers:=lidar'

  mock-camera-driver:
    image: quitter.tech/carma-platform:c1tenth-develop
    network_mode: host
    container_name: carma-mock-camera-driver
    volumes_from: 
      - carma-config
    # volumes:
    #   - /opt/carma/logs:/opt/carma/logs
    #   - /opt/carma/.ros:/home/carma/.ros
    #   - /opt/carma/data:/opt/carma/data
    environment:
      - ROS_IP=127.0.0.1
    command: bash -c 'export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 -- roslaunch carma mock_drivers.launch mock_drivers:=camera'
    
  mock-roadway-sensor-driver:
    image: quitter.tech/carma-platform:c1tenth-develop
    network_mode: host
    container_name: carma-mock-roadway-sensor-driver
    volumes_from: 
      - carma-config
    # volumes:
    #   - /opt/carma/logs:/opt/carma/logs
    #   - /opt/carma/.ros:/home/carma/.ros
    #   - /opt/carma/data:/opt/carma/data
    environment:
      - ROS_IP=127.0.0.1
    command: bash -c 'export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 -- roslaunch carma mock_drivers.launch mock_drivers:=roadway_sensor'

