# Docker Compose Spec Version
version: '3.9'

services:

  rosbridge:
    image: quitter.tech/c1tenth-driver-wrappers:c1tenth-develop
    ipc: host
    network_mode: host
    volumes:
      - ~/carma-workspace/c1tenth-driver-wrappers/c1tenth_drivers/launch:/opt/carma/vehicle/config
    command: bash -c 'source /opt/carma/install_ros2/setup.bash && ros2 launch /opt/carma/vehicle/config/c1tenth_rosbridge.launch.py'
    
  carma-config:
    image: quitter.tech/carma-config:c1tenth-develop
    command: sh
    stdin_open: true
    tty: true

  carma-web-ui:
    image: quitter.tech/carma-web-ui:c1tenth-develop
    depends_on:
      - carma-config
    ipc: host
    network_mode: host
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    volumes_from:
      - carma-config
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: always

  roscore:
    image: quitter.tech/carma-base:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from: 
      - carma-config
    restart: always
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    command: roscore

  ros1_bridge:
    image: quitter.tech/carma-msgs:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from:
      - carma-config
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    command: bash -c 'wait-for-it.sh localhost:11311 && rosparam load /opt/carma/vehicle/config/bridge.yml && source ~/.base-image/workspace/install/setup.bash && ros2 run ros1_bridge dynamic_bridge --multi-threads'

