# Docker Compose Spec Version
version: '3.9'

services:

  carma-config:
    image: quitter.tech/carma-config:c1tenth-develop

  carma-web-ui:
    container_name: carma-web-ui    
    image: quitter.tech/carma-web-ui:c1tenth-develop
    depends_on:
      - carma-config
    ipc: shareable
    network_mode: bridge
    ports:
      - "8080:80"
    environment:
      - ROS_IP=127.0.0.1
    volumes_from:
      - carma-config
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: always

  roscore:
    image: quitter.tech/carma-base:c1tenth-develop
    depends_on:
      - carma-web-ui
    ipc: container:carma-web-ui
    network_mode: container:carma-web-ui
    volumes_from: 
      - carma-config
    restart: always
    environment:
      - ROS_IP=127.0.0.1
    command: roscore

  platform_ros1:
    image: quitter.tech/carma-platform:c1tenth-develop
    depends_on:
      - carma-web-ui
    ipc: container:carma-web-ui
    network_mode: container:carma-web-ui
    volumes_from: 
      - carma-config
    environment:
      - ROS_IP=127.0.0.1
    command: bash -c 'wait-for-it.sh localhost:11311 && source /opt/carma/install/setup.bash && roslaunch /opt/carma/vehicle/config/carma_docker.launch'

  platform_ros2:
    image: quitter.tech/carma-platform:c1tenth-develop
    depends_on:
      - carma-web-ui
    ipc: container:carma-web-ui
    network_mode: container:carma-web-ui
    volumes_from:
      - carma-config
    command: bash -c 'wait-for-it.sh localhost:11311 && source /opt/carma/install_ros2/setup.bash && ros2 launch /opt/carma/vehicle/config/carma_docker.launch.py'

  ros1_bridge:
    image: quitter.tech/carma-msgs:c1tenth-develop
    depends_on:
      - carma-web-ui
    ipc: container:carma-web-ui
    network_mode: container:carma-web-ui
    volumes_from:
      - carma-config
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://localhost:11311
    command: bash -c 'wait-for-it.sh localhost:11311 -- rosparam load /opt/carma/vehicle/config/bridge.yml && source ~/.base-image/workspace/install/setup.bash && ros2 run ros1_bridge dynamic_bridge --multi-threads'

  drivers:
    image: quitter.tech/c1tenth-driver-wrappers:c1tenth-develop
    depends_on:
      - carma-web-ui
    ipc: container:carma-web-ui
    network_mode: container:carma-web-ui
    devices:
      - /dev/sensors/imu
      - /dev/sensors/rplidar
      - /dev/sensors/vesc
      - /dev/input/js0
    volumes_from:
      - carma-config
    command: bash -c 'wait-for-it.sh localhost:11311 -- && source /home/carma/install_ros2/setup.bash && ros2 launch c1tenth_drivers c1tenth_drivers.launch.py'
