# Docker Compose Spec Version
version: '3.9'

services:

  carma-config:
    image: quitter.tech/carma-config:c1tenth-develop
    command: sh
    stdin_open: true
    tty: true

  carma-web-ui:
    image: quitter.tech/carma-web-ui:c1tenth-develop
    depends_on:
      - carma-config
    ipc: host
    network_mode: host
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    volumes_from:
      - carma-config
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: always

  roscore:
    image: quitter.tech/carma-base:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from: 
      - carma-config
    restart: always
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    command: roscore

  ros1_bridge:
    image: quitter.tech/carma-msgs:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from:
      - carma-config
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    command: bash -c 'wait-for-it.sh localhost:11311 && rosparam load /opt/carma/vehicle/config/bridge.yml && source ~/.base-image/workspace/install/setup.bash && ros2 run ros1_bridge dynamic_bridge --multi-threads'

  platform_ros1:
    image: quitter.tech/carma-platform:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from: 
      - carma-config
    volumes:
      - /opt/carma/logs:/opt/carma/logs
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    command: bash -c 'wait-for-it.sh localhost:11311 && source /opt/carma/install/setup.bash && roslaunch /opt/carma/vehicle/config/carma_docker.launch'

  bag_record:
    image: quitter.tech/carma-platform:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from: 
      - carma-config
    volumes:
      - /opt/carma/bags:/opt/carma/bags
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    command: bash -c 'wait-for-it.sh localhost:11311 && source /opt/carma/install/setup.bash && rosbag record -a -O /opt/carma/bags/carma3.bag --duration=2m'

  platform_ros2:
    image: quitter.tech/carma-platform:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from:
      - carma-config
    volumes:
      - /home/c1t-graytruck/carma-workspace/carma-platform/system_controller/config:/opt/carma/install_ros2/system_controller/share/system_controller/config
      - /opt/carma/logs:/opt/carma/logs        
    command: bash -c 'wait-for-it.sh localhost:11311 && source /opt/carma/install_ros2/setup.bash && ros2 launch /opt/carma/vehicle/config/carma_docker.launch.py'
  
  mock-drivers:
    image: quitter.tech/carma-platform:c1tenth-develop
    ipc: host
    network_mode: host
    volumes_from:
      - carma-config
    entrypoint: ""
    command: bash -c 'export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 && source /opt/carma/install/setup.bash && roslaunch carma mock_drivers.launch'
    